/**
 * 60 real, published board games with real BoardGameGeek IDs, disjoint from
 * `DEMO_GAMES`/`DEMO_EXPANSIONS` by title (checked in demo-private-collection.test.ts).
 * Stands in for a real BGG collection sync (blocked in this environment, see the
 * comment in `demo-games.ts`) — two demo meeples get 30 entries each from this pool.
 * `imageUrl` is left `null` throughout: no live BGG/Wikimedia access was available
 * from this environment to confirm a real cover image URL for any of these titles,
 * and a guessed URL would be worse than none (same policy as `demo-games.ts`).
 */
export type DemoPrivateCollectionGame = {
  title: string;
  bggId: number;
  imageUrl: string | null;
  minPlayers: number | null;
  maxPlayers: number | null;
  playTimeMinutes: number | null;
};

export const DEMO_PRIVATE_COLLECTION_POOL: DemoPrivateCollectionGame[] = [
  {
    title: "Dune: Imperium",
    bggId: 316554,
    imageUrl: null,
    minPlayers: 1,
    maxPlayers: 4,
    playTimeMinutes: 60,
  },
  {
    title: "Cartographers",
    bggId: 263918,
    imageUrl: null,
    minPlayers: 1,
    maxPlayers: 100,
    playTimeMinutes: 45,
  },
  {
    title: "Wyrmspan",
    bggId: 410201,
    imageUrl: null,
    minPlayers: 1,
    maxPlayers: 5,
    playTimeMinutes: 90,
  },
  {
    title: "Nova Luna",
    bggId: 284435,
    imageUrl: null,
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMinutes: 30,
  },
  {
    title: "Ankh: Gods of Egypt",
    bggId: 285967,
    imageUrl: null,
    minPlayers: 2,
    maxPlayers: 5,
    playTimeMinutes: 90,
  },
  {
    title: "Deep Sea Adventure",
    bggId: 169654,
    imageUrl: null,
    minPlayers: 2,
    maxPlayers: 6,
    playTimeMinutes: 30,
  },
  {
    title: "Twice as Clever!",
    bggId: 269210,
    imageUrl: null,
    minPlayers: 1,
    maxPlayers: 4,
    playTimeMinutes: 30,
  },
  {
    title: "Eclipse: Second Dawn for the Galaxy",
    bggId: 246900,
    imageUrl: null,
    minPlayers: 2,
    maxPlayers: 6,
    playTimeMinutes: 180,
  },
  {
    title: "Cosmic Encounter",
    bggId: 39463,
    imageUrl: null,
    minPlayers: 3,
    maxPlayers: 5,
    playTimeMinutes: 120,
  },
  {
    title: "Star Realms",
    bggId: 147020,
    imageUrl: null,
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMinutes: 20,
  },
  {
    title: "Space Base",
    bggId: 242302,
    imageUrl: null,
    minPlayers: 2,
    maxPlayers: 5,
    playTimeMinutes: 90,
  },
  {
    title: "Raiders of the North Sea",
    bggId: 170042,
    imageUrl: null,
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMinutes: 80,
  },
  {
    title: "Nidavellir",
    bggId: 293014,
    imageUrl: null,
    minPlayers: 2,
    maxPlayers: 5,
    playTimeMinutes: 45,
  },
  {
    title: "Machi Koro 2",
    bggId: 340364,
    imageUrl: null,
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMinutes: 30,
  },
  {
    title: "Tapestry",
    bggId: 286096,
    imageUrl: null,
    minPlayers: 1,
    maxPlayers: 5,
    playTimeMinutes: 90,
  },
  {
    title: "Underwater Cities",
    bggId: 247763,
    imageUrl: null,
    minPlayers: 1,
    maxPlayers: 4,
    playTimeMinutes: 100,
  },
  {
    title: "Gaia Project",
    bggId: 220308,
    imageUrl: null,
    minPlayers: 1,
    maxPlayers: 4,
    playTimeMinutes: 150,
  },
  {
    title: "That's Pretty Clever!",
    bggId: 244522,
    imageUrl: null,
    minPlayers: 1,
    maxPlayers: 4,
    playTimeMinutes: 30,
  },
  {
    title: "Gizmos",
    bggId: 246192,
    imageUrl: null,
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMinutes: 40,
  },
  {
    title: "Hues and Cues",
    bggId: 302520,
    imageUrl: null,
    minPlayers: 2,
    maxPlayers: 10,
    playTimeMinutes: 30,
  },
  {
    title: "Boonlake",
    bggId: 343905,
    imageUrl: null,
    minPlayers: 1,
    maxPlayers: 4,
    playTimeMinutes: 120,
  },
  {
    title: "Faraway",
    bggId: 385761,
    imageUrl: null,
    minPlayers: 2,
    maxPlayers: 5,
    playTimeMinutes: 30,
  },
  {
    title: "Twilight Imperium: Fourth Edition",
    bggId: 233078,
    imageUrl: null,
    minPlayers: 3,
    maxPlayers: 6,
    playTimeMinutes: 240,
  },
  {
    title: "Alien Frontiers",
    bggId: 48726,
    imageUrl: null,
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMinutes: 90,
  },
  {
    title: "Glory to Rome",
    bggId: 19857,
    imageUrl: null,
    minPlayers: 2,
    maxPlayers: 5,
    playTimeMinutes: 60,
  },
  {
    title: "Suburbia",
    bggId: 123260,
    imageUrl: null,
    minPlayers: 1,
    maxPlayers: 4,
    playTimeMinutes: 90,
  },
  {
    title: "Endeavor: Age of Sail",
    bggId: 233398,
    imageUrl: null,
    minPlayers: 2,
    maxPlayers: 5,
    playTimeMinutes: 75,
  },
  {
    title: "The Great Zimbabwe",
    bggId: 111341,
    imageUrl: null,
    minPlayers: 3,
    maxPlayers: 5,
    playTimeMinutes: 150,
  },
  {
    title: "Yellow & Yangtze",
    bggId: 244114,
    imageUrl: null,
    minPlayers: 2,
    maxPlayers: 5,
    playTimeMinutes: 90,
  },
  {
    title: "Pandemic Legacy: Season 2",
    bggId: 221107,
    imageUrl: null,
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMinutes: 60,
  },
  {
    title: "Clank! In! Space!: A Deck-Building Adventure",
    bggId: 233371,
    imageUrl: null,
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMinutes: 60,
  },
  {
    title: "Kingsburg",
    bggId: 27162,
    imageUrl: null,
    minPlayers: 2,
    maxPlayers: 5,
    playTimeMinutes: 90,
  },
  {
    title: "Innovation",
    bggId: 63888,
    imageUrl: null,
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMinutes: 30,
  },
  {
    title: "Aeon's End",
    bggId: 191189,
    imageUrl: null,
    minPlayers: 1,
    maxPlayers: 4,
    playTimeMinutes: 60,
  },
  {
    title: "Mystic Vale",
    bggId: 194607,
    imageUrl: null,
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMinutes: 30,
  },
  {
    title: "Hero Realms",
    bggId: 198994,
    imageUrl: null,
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMinutes: 15,
  },
  {
    title: "Sub Terra",
    bggId: 204472,
    imageUrl: null,
    minPlayers: 1,
    maxPlayers: 6,
    playTimeMinutes: 45,
  },
  {
    title: "The Isle of Cats",
    bggId: 281259,
    imageUrl: null,
    minPlayers: 1,
    maxPlayers: 4,
    playTimeMinutes: 60,
  },
  {
    title: "Container",
    bggId: 26990,
    imageUrl: null,
    minPlayers: 3,
    maxPlayers: 5,
    playTimeMinutes: 150,
  },
  {
    title: "Karuba",
    bggId: 183251,
    imageUrl: null,
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMinutes: 30,
  },
  {
    title: "7 Wonders Duel",
    bggId: 173346,
    imageUrl: null,
    minPlayers: 2,
    maxPlayers: 2,
    playTimeMinutes: 30,
  },
  {
    title: "Lords of Waterdeep",
    bggId: 110327,
    imageUrl: null,
    minPlayers: 2,
    maxPlayers: 5,
    playTimeMinutes: 60,
  },
  {
    title: "A Feast for Odin",
    bggId: 177736,
    imageUrl: null,
    minPlayers: 1,
    maxPlayers: 4,
    playTimeMinutes: 120,
  },
  {
    title: "Barony",
    bggId: 167513,
    imageUrl: null,
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMinutes: 45,
  },
  {
    title: "New York Zoo",
    bggId: 300877,
    imageUrl: null,
    minPlayers: 1,
    maxPlayers: 5,
    playTimeMinutes: 60,
  },
  {
    title: "Reef",
    bggId: 244228,
    imageUrl: null,
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMinutes: 40,
  },
  {
    title: "Detective: A Modern Crime Board Game",
    bggId: 223321,
    imageUrl: null,
    minPlayers: 1,
    maxPlayers: 5,
    playTimeMinutes: 90,
  },
  {
    title: "Chronicles of Crime",
    bggId: 239188,
    imageUrl: null,
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMinutes: 60,
  },
  {
    title: "Five Tribes: The Djinns of Naqala",
    bggId: 157354,
    imageUrl: null,
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMinutes: 80,
  },
  {
    title: "Bärenpark",
    bggId: 219513,
    imageUrl: null,
    minPlayers: 1,
    maxPlayers: 4,
    playTimeMinutes: 60,
  },
  {
    title: "Welcome To...",
    bggId: 233867,
    imageUrl: null,
    minPlayers: 1,
    maxPlayers: 100,
    playTimeMinutes: 25,
  },
  {
    title: "Evolution",
    bggId: 155703,
    imageUrl: null,
    minPlayers: 2,
    maxPlayers: 6,
    playTimeMinutes: 60,
  },
  {
    title: "Wingspan: Oceania Expansion",
    bggId: 300580,
    imageUrl: null,
    minPlayers: 1,
    maxPlayers: 5,
    playTimeMinutes: 70,
  },
  {
    title: "Root: The Riverfolk Expansion",
    bggId: 241386,
    imageUrl: null,
    minPlayers: 2,
    maxPlayers: 6,
    playTimeMinutes: 90,
  },
  {
    title: "The Manhattan Project: Energy Empire",
    bggId: 176734,
    imageUrl: null,
    minPlayers: 1,
    maxPlayers: 5,
    playTimeMinutes: 100,
  },
  {
    title: "Boss Monster: The Dungeon Building Card Game",
    bggId: 131835,
    imageUrl: null,
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMinutes: 30,
  },
  {
    title: "Skull King",
    bggId: 150145,
    imageUrl: null,
    minPlayers: 2,
    maxPlayers: 6,
    playTimeMinutes: 30,
  },
  {
    title: "Kingdom Builder",
    bggId: 107529,
    imageUrl: null,
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMinutes: 45,
  },
  {
    title: "Village",
    bggId: 104006,
    imageUrl: null,
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMinutes: 90,
  },
  {
    title: "Trickerion: Legends of Illusion",
    bggId: 163068,
    imageUrl: null,
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMinutes: 100,
  },
];
